version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: foreks
    ports:
      - "5432:5432"

  currency-calculator:
    build: .
    ports:
      - "8888:7006"
    depends_on:
      - postgres
